name: delivery_app
description: "A Flutter delivery app"

publish_to: 'none' # no la publicaremos en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  flutter_recaptcha_v2_compat: ^1.0.5
  webview_flutter: ^4.2.2
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.0
  mobile_scanner: ^3.5.3
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  local_auth: ^2.1.6
  url_launcher: ^6.2.5
  jwt_decoder: ^2.0.1
  fl_chart: ^0.63.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker: ^0.8.7+3
  http: ^1.3.0
  http_parser: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/captcha.html
    - assets/sounds/beep.wav
    - assets/icons/moto.png

